{"continentes":[
    {"norteamerica":[
        {"numPregunta":8,"respuesta":1},
        {"numPregunta":9,"respuesta":1}
                    ]
    },
    { "sudamerica":[
         {"numPregunta":3,"respuesta":1},
         {"numPregunta":6,"respuesta":1}
                    ]
    },
     {"europa":[
         {"numPregunta":57,"respuesta":1},
         {"numPregunta":11,"respuesta":1},
         {"numPregunta":12,"respuesta":1}
                ]
     },
     {"africa":[
         {"numPregunta":1,"respuesta":1},
         {"numPregunta":2,"respuesta":1}
                ]
     },
     {"asia":[
         {"numPregunta":4,"respuesta":1},
         {"numPregunta":5,"respuesta":1},
         {"numPregunta":10,"respuesta":1}
                ]
     },
     {"oceania":[
         {"numPregunta":14,"respuesta":1},
         {"numPregunta":15,"respuesta":1}
                ]
     }
 ]
}